import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import Enum, engine_from_config, pool
from sqlalchemy.schema import CheckConstraint, SchemaItem
from step_by_step_core.db import Base

config = context.config

# The connection URL comes from the environment, never from alembic.ini —
# the compose stack and CI inject it per deployment.
config.set_main_option("sqlalchemy.url", os.environ["DATABASE_URL"])

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Autogenerate target: every table inherits step_by_step_core.db.Base, and
# importing the model modules is what registers them on its metadata.
import step_by_step_api.accounts.models  # noqa: E402
import step_by_step_api.extension.models  # noqa: E402
import step_by_step_api.workflows.models  # noqa: E402, F401

target_metadata = Base.metadata

# Every non-native `Enum` column writes a check constraint of its own, and
# alembic 1.19 compares only one side of it: the metadata side drops
# type-bound constraints from the comparison, while the reflected side has no
# way to tell one apart, so each autogenerated revision proposes dropping a
# constraint nobody removed. Naming them here is the fix, and the names come
# from the metadata on every run — a column a model really drops leaves this
# set with it, and autogenerate proposes that drop as it should. Delete once
# alembic recognises a reflected type-bound constraint (issue `t6xbdg`).
TYPE_BOUND_CHECKS = {
    (table.name, column.type.name)
    for table in target_metadata.tables.values()
    for column in table.columns
    if isinstance(column.type, Enum)
    and not column.type.native_enum
    and column.type.create_constraint
}


def include_object(
    obj: SchemaItem,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: SchemaItem | None,
) -> bool:
    """Everything but a reflected check constraint one of our own Enums wrote."""
    if reflected and isinstance(obj, CheckConstraint):
        return (obj.table.name, name) not in TYPE_BOUND_CHECKS
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        include_object=include_object,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
