"""The migration runner against a real Postgres."""

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError
from step_by_step_api.db import get_engine

pytestmark = pytest.mark.integration


def head_revision(runner: Config) -> str | None:
    return ScriptDirectory.from_config(runner).get_current_head()


def stamped_revision() -> str:
    with get_engine().connect() as connection:
        version = connection.execute(text("SELECT version_num FROM alembic_version"))
        return version.scalar_one()


def test_migrating_a_fresh_database_reaches_head(migration_runner: Config) -> None:
    assert stamped_revision() == head_revision(migration_runner)


def test_migrating_again_changes_nothing(migration_runner: Config) -> None:
    command.upgrade(migration_runner, "head")

    assert stamped_revision() == head_revision(migration_runner)


def test_autogenerating_against_head_proposes_nothing(
    migration_runner: Config,
) -> None:
    """A database at head and the models it came from are the same schema.

    `alembic check` raises when they differ, so this fails on any diff an
    autogenerated revision would carry — the type-bound check constraints
    `alembic/env.py` filters out included.
    """
    command.check(migration_runner)


def test_a_role_outside_the_three_is_refused() -> None:
    """The filter hides those constraints from autogenerate, not from Postgres."""
    with get_engine().begin() as connection:
        org_id = connection.execute(
            text(
                "INSERT INTO organizations (id, name) VALUES (gen_random_uuid(), "
                "'Roles') RETURNING id"
            )
        ).scalar_one()
        user_id = connection.execute(
            text(
                "INSERT INTO users (id, email) VALUES (gen_random_uuid(), "
                "'roles@example.com') RETURNING id"
            )
        ).scalar_one()

    with (
        pytest.raises(IntegrityError, match="membership_role"),
        get_engine().begin() as connection,
    ):
        connection.execute(
            text(
                "INSERT INTO memberships (org_id, user_id, role) "
                "VALUES (:org_id, :user_id, 'intern')"
            ),
            {"org_id": org_id, "user_id": user_id},
        )
