"""workflow document store

The two Workflow tables: the Workflow itself, org-owned and carrying both
timeouts, and the one Draft row that holds its document as JSONB.

Autogenerate also proposed dropping the `invitation_role` and
`membership_role` check constraints. That is noise, not a change: SQLAlchemy's
non-native `Enum` writes those constraints but does not present them for
comparison, so every autogenerated revision after the accounts schema will
propose the same two drops. They are removed here by hand; `t6xbdg` holds
the permanent fix.

Revision ID: 1be493f219da
Revises: accbfe792ea3
Create Date: 2026-08-18 06:24:22.751873

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1be493f219da"
down_revision: str | Sequence[str] | None = "accbfe792ea3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "workflows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("default_step_timeout_ms", sa.Integer(), nullable=False),
        sa.Column("takeover_timeout_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflows_org_id"), "workflows", ["org_id"], unique=False)
    op.create_table(
        "workflow_drafts",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workflow_id"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("workflow_drafts")
    op.drop_index(op.f("ix_workflows_org_id"), table_name="workflows")
    op.drop_table("workflows")
